name: ucan
description: "A new Flutter project." 
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
 
version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0' 
dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.10+1
  equatable: ^2.0.5
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  firebase_storage:
  cloud_firestore:
  sqflite: ^2.3.2
  sqlbrite: ^2.7.0
  provider: ^6.1.2
  path_provider: ^2.1.2
  pinput: ^4.0.0
  flutter_secure_storage: ^9.0.0
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4
  get_it: ^7.7.0
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  build_runner: ^2.4.9
  shimmer: ^3.0.0
  im_stepper: ^1.0.1+1
  flutter_tabler_icons: ^1.29.0
  firebase_database: ^10.5.7
  logging_flutter: ^2.0.1
  dio: ^5.4.3+1
  shared_preferences: ^2.0.16
  freezed_annotation: ^2.1.0
  connectivity_plus: ^3.0.4
  firebase_performance: ^0.9.0+9
  lottie: ^3.1.2
  flutter_localizations:
    sdk: flutter


dependency_overrides:
    intl: ^0.19.0



dev_dependencies:
  flutter_test:
    sdk: flutter 
  flutter_lints: ^2.0.0
  another_flushbar: ^1.12.29
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/png/logo.png" 
  
 
flutter:

  uses-material-design: true

  assets:
    - assets/svg/
    - assets/png/
    - assets/animations/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/Roboto-BlackItalic.ttf
          weight: 900
          style: italic


   
